//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_ChainStores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders_Details_Store = new HashSet<Orders_Details_Store>();
            this.Orders_Details_Suppliers = new HashSet<Orders_Details_Suppliers>();
            this.ProductAvailability_Suppliers = new HashSet<ProductAvailability_Suppliers>();
            this.ProductAvailability_Stores = new HashSet<ProductAvailability_Stores>();
        }
        [DisplayName("ID")]
        public int ProductID { get; set; }
        [DisplayName("Название товара")]
        public string ProductName { get; set; }
        [DisplayName("Цена закупки")]
        public Nullable<decimal> PurchasePrice { get; set; }
        [DisplayName("Цена продажи")]
        public Nullable<decimal> SalePrice { get; set; }
        [DisplayName("Характеристики")]
        public string DescriptionProduct { get; set; }
        [DisplayName("Место на складе")]
        public Nullable<int> Place { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Details_Store> Orders_Details_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Details_Suppliers> Orders_Details_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAvailability_Suppliers> ProductAvailability_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAvailability_Stores> ProductAvailability_Stores { get; set; }
    }
}
